using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using SporTime.Model;
using SporTime.ViewModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace SporTime
{
    [Activity(Label = "MainPageActivity", LaunchMode = Android.Content.PM.LaunchMode.SingleTop)]
    public class MainPageActivity : Activity
    {
        ListView lvReservations;
        private static List<Reservation> myReservations = new List<Reservation>();
        private static bool isFirstLoad = true;
        string FieldName, ReservationDate, ReservationTime;


        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            // Safety check for Firebase if navigating from login
            if (Firebase.FirebaseApp.Instance == null)
                Firebase.FirebaseApp.InitializeApp(this);

            SetContentView(Resource.Layout.main_page);

            lvReservations = FindViewById<ListView>(Resource.Id.lvReservations);


            // dummy data for testing
            // reservation id is not real. the real one is generated by postgres
            
        
            if (isFirstLoad)
            {
                // Initial Dummy Data
                myReservations.Add(new Reservation { ReservationId = 101, FieldName = "Main Soccer Field", StartingTime = new DateTime(2026, 1, 15, 18, 0, 0) });
                isFirstLoad = false;
            }

            ProcessIntentData(Intent);

            lvReservations.Adapter = new ReservationAdapter(this, myReservations);
            InitializeNavigation();
        }

        protected override void OnNewIntent(Intent intent)
        {
            base.OnNewIntent(intent);
            // Important: Update the Activity's Intent so ProcessIntentData uses the NEW one
            Intent = intent;

            ProcessIntentData(intent);

            // Refresh the list immediately
            ((BaseAdapter)lvReservations.Adapter).NotifyDataSetChanged();
        }
        private void ProcessIntentData(Intent intent)
        {
            var fieldName = intent.GetStringExtra("FieldName");
            var dateStr = intent.GetStringExtra("ReservationDate");
            var timeStr = intent.GetStringExtra("ReservationTime");

            if (!string.IsNullOrEmpty(fieldName) && !string.IsNullOrEmpty(dateStr) && !string.IsNullOrEmpty(timeStr))
            {
                try
                {
                    var times = timeStr.Split(" - ");
                    DateTime startParsed = DateTime.ParseExact($"{dateStr} {times[0]}", "dd/MM/yyyy HH:mm", System.Globalization.CultureInfo.InvariantCulture);
                    DateTime endParsed = DateTime.ParseExact($"{dateStr} {times[1]}", "dd/MM/yyyy HH:mm", System.Globalization.CultureInfo.InvariantCulture);

                    myReservations.Add(new Reservation
                    {
                        ReservationId = 6, // This should ideally come from the backend after saving the reservation
                        FieldName = fieldName,
                        StartingTime = startParsed,

                    });

                    // Clear these so they don't get re-added on rotation
                    intent.RemoveExtra("FieldName");
                    intent.RemoveExtra("ReservationDate");
                    intent.RemoveExtra("ReservationTime");
                }
                catch (Exception ex)
                {
                    Android.Util.Log.Error("SporTime", "Parsing Error: " + ex.Message);
                }
            }
        }

        private void InitializeNavigation()
        {
            var navNew = FindViewById<LinearLayout>(Resource.Id.navNew);
            var navAccount = FindViewById<LinearLayout>(Resource.Id.navAccount);
            var navHome = FindViewById<LinearLayout>(Resource.Id.navHome);

            navNew.Click += (s, e) => {
                StartActivity(typeof(PickFieldPageActivity));
            };

            navAccount.Click += (s, e) => {
                StartActivity(typeof(AccountPageActivity));
            };
        }
    }
}