using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using SporTime.Model;
using SporTime.ViewModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace SporTime
{
    [Activity(Label = "MainPageActivity")]
    public class MainPageActivity : Activity
    {
        ListView lvReservations;
        List<Reservation> myReservations;
        string FieldName, ReservationDate, ReservationTime;


        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            // Safety check for Firebase if navigating from login
            if (Firebase.FirebaseApp.Instance == null)
                Firebase.FirebaseApp.InitializeApp(this);

            SetContentView(Resource.Layout.main_page);

            lvReservations = FindViewById<ListView>(Resource.Id.lvReservations);


            // dummy data for testing
            // reservation id is not real. the real one is generated by postgres
            myReservations = new List<Reservation>
        {
            new Reservation
            {
                Reservation_Id = "101",
                FieldName = "Main Soccer Field",
                Start = new DateTime(2026, 1, 15, 18, 0, 0),
                End = new DateTime(2026, 1, 15, 19, 0, 0)
            },
            new Reservation
            {
                Reservation_Id = "102",
                FieldName = "Tennis Court B",
                Start = new DateTime(2026, 1, 16, 10, 0, 0),
                End = new DateTime(2026, 1, 16, 11, 0, 0)
            }


        };

            var fieldName = Intent.GetStringExtra("FieldName");
            var dateStr = Intent.GetStringExtra("ReservationDate");
            var timeStr = Intent.GetStringExtra("ReservationTime");

            if (!string.IsNullOrEmpty(fieldName) && !string.IsNullOrEmpty(dateStr) && !string.IsNullOrEmpty(timeStr))
            {
                try
                {
                    // 1. Split the time range "08:00 - 09:00" into two parts
                    var times = timeStr.Split(" - ");
                    string startTime = times[0]; // "08:00"
                    string endTime = times[1];   // "09:00"

                    // 2. Combine and Parse
                    // We use InvariantCulture to avoid errors with different phone language settings
                    DateTime startParsed = DateTime.ParseExact($"{dateStr} {startTime}", "dd/MM/yyyy HH:mm", System.Globalization.CultureInfo.InvariantCulture);
                    DateTime endParsed = DateTime.ParseExact($"{dateStr} {endTime}", "dd/MM/yyyy HH:mm", System.Globalization.CultureInfo.InvariantCulture);

                    myReservations.Add(new Reservation
                    {
                        Reservation_Id = Guid.NewGuid().ToString().Substring(0, 5),
                        FieldName = fieldName,
                        Start = startParsed,
                        End = endParsed
                    });
                }
                catch (Exception ex)
                {
                    // Log if parsing fails due to unexpected format
                    Android.Util.Log.Error("SporTime", "Parsing Error: " + ex.Message);
                    throw new FormatException("Date or Time format is incorrect.");
                }

                // 2. Set the Adapter
                

            }
            lvReservations.Adapter = new ReservationAdapter(this, myReservations);

            InitializeNavigation();
        }

        //private DateTime SortDateAndTime(string dateStr, string timeStr)
        //{
            
        //}

        private void InitializeNavigation()
        {
            var navNew = FindViewById<LinearLayout>(Resource.Id.navNew);
            var navAccount = FindViewById<LinearLayout>(Resource.Id.navAccount);
            var navHome = FindViewById<LinearLayout>(Resource.Id.navHome);

            navNew.Click += (s, e) => {
                StartActivity(typeof(PickFieldPageActivity));
            };

            navAccount.Click += (s, e) => {
                StartActivity(typeof(AccountPageActivity));
            };
        }
    }
}